// src/data/carsData.js

export const cars = [
    {
      id: 1,
      name: 'Toyota Avanza',
      description: 'Best for Family Trips',
      seats: 6,
      airConditioning: true,
      transmission: 'Manual',
      price: 300000,
      location: 'Jakarta',
      image: 'https://toyotagarutofficial.com/wp-content/uploads/2021/07/7_White-min.png',
      availableFrom: '2025-04-01',
      availableUntil: '2025-04-30',
      available: true,
    },
    {
      id: 2,
      name: 'Honda CR-V',
      description: 'Comfortable SUV for Long Drives',
      seats: 5,
      airConditioning: true,
      transmission: 'Automatic',
      price: 400000,
      location: 'Bali',
      image: 'https://www.honda-arta.com/lib/images/item/crv%20putih.png',
      availableFrom: '2025-04-10',
      availableUntil: '2025-04-20',
      available: true,
    },
    {
      id: 3,
      name: 'Suzuki Swift',
      description: 'Compact City Car',
      seats: 5,
      airConditioning: true,
      transmission: 'Manual',
      price: 250000,
      location: 'Surabaya',
      image: 'https://media.umbraco.io/suzuki-gb/rr3pz3kd/10816_suzuki_swift_510_r1.jpg',
      availableFrom: '2025-04-05',
      availableUntil: '2025-04-15',
      available: false,
    },
    {
      id: 4,
      name: 'BMW X5',
      description: 'Luxury SUV for Long Trips',
      seats: 5,
      airConditioning: true,
      transmission: 'Automatic',
      price: 1200000,
      location: 'Jakarta',
      image: 'https://www.bmw.cc/content/dam/bmw/common/all-models/x-series/x5/2021/navigation/bmw-X5-modelfinder-890x501.png.asset.1633354188466.png',
      availableFrom: '2025-04-20',
      availableUntil: '2025-04-25',
      available: true,
    },
    {
      id: 5,
      name: 'Toyota Innova',
      description: 'Great for Family Travel',
      seats: 7,
      airConditioning: true,
      transmission: 'Automatic',
      price: 500000,
      location: 'Jakarta',
      image: 'https://www.korinatour.co.id/wp-content/uploads/2018/10/white-innova-png-5.png',
      availableFrom: '2025-04-01',
      availableUntil: '2025-04-30',
      available: true,
    },
    // Add more cars here as needed
  ];
  